services:
  rabbitmq:
    image: rabbitmq:4-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./storage:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend-network

networks:
  backend-network:
    external: true
