services:
  postgres:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root13
    ports:
      - "5432:5432"
    volumes:
      - ./storage:/var/lib/postgresql/data